#!/usr/bin/env bash

protected_branch=${GIT_PROTECTED_BRANCH:-master}
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*refs\/heads\/\(.*\),\1,')
RANDOM_CHAR=$(( ( RANDOM % 9 )  + 1 ))

if [ $protected_branch = $current_branch ]
then
    read -p "You're about to push '$current_branch', is that what you intended? [$RANDOM_CHAR|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E "^[$RANDOM_CHAR]$" > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
